Name:           ros-kinetic-pr2-calibration-launch
Version:        1.0.11
Release:        0%{?dist}
Summary:        ROS pr2_calibration_launch package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/pr2_calibration_launch
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-calibration-estimation
Requires:       ros-kinetic-calibration-launch
Requires:       ros-kinetic-calibration-msgs
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-image-cb-detector
Requires:       ros-kinetic-image-view
Requires:       ros-kinetic-kdl-parser
Requires:       ros-kinetic-laser-cb-detector
Requires:       ros-kinetic-laser-joint-processor
Requires:       ros-kinetic-laser-joint-projector
Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-monocam-settler
Requires:       ros-kinetic-pr2-dense-laser-snapshotter
Requires:       ros-kinetic-pr2-teleop
Requires:       ros-kinetic-python-orocos-kdl
Requires:       ros-kinetic-robot-mechanism-controllers
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-rostest
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-stereo-image-proc
BuildRequires:  ros-kinetic-calibration-estimation
BuildRequires:  ros-kinetic-calibration-launch
BuildRequires:  ros-kinetic-calibration-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-image-cb-detector
BuildRequires:  ros-kinetic-image-view
BuildRequires:  ros-kinetic-kdl-parser
BuildRequires:  ros-kinetic-laser-cb-detector
BuildRequires:  ros-kinetic-laser-joint-processor
BuildRequires:  ros-kinetic-laser-joint-projector
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-monocam-settler
BuildRequires:  ros-kinetic-pr2-dense-laser-snapshotter
BuildRequires:  ros-kinetic-pr2-teleop
BuildRequires:  ros-kinetic-python-orocos-kdl
BuildRequires:  ros-kinetic-robot-mechanism-controllers
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-stereo-image-proc

%description
Launch files and configuration files needed to run the calibration pipeline on
PR2. This package is still experimental. Expect large changes tp occur.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Apr 20 2018 Dave Feil-Seifer <dave@cse.unr.edu> - 1.0.11-0
- Autogenerated by Bloom

