Name:           ros-kinetic-dense-laser-assembler
Version:        1.0.11
Release:        0%{?dist}
Summary:        ROS dense_laser_assembler package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/dense_laser_assembler
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-calibration-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-roscpp-serialization
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-settlerlib
Requires:       ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-calibration-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-roscpp-serialization
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-settlerlib
BuildRequires:  ros-kinetic-std-msgs

%description
Stores streaming data from a laser sensor in a dense representation. This allows
the user to do 'image-like' processing on the data, and can also be used for
very fast approx neighborhood searches. This package is still experimental and
unstable. Expect its APIs to change.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Apr 20 2018 Dave Feil-Seifer <dave@cse.unr.edu> - 1.0.11-0
- Autogenerated by Bloom

